# fly.toml app configuration file generated for janebot on 2026-02-01T12:16:21+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'janebot'
primary_region = 'syd'

[build]
  dockerfile = 'Dockerfile'

[env]
  AGENT_MODE = 'smart'
  NODE_ENV = 'production'
  SESSIONS_FILE = '/data/sessions.json'

[mounts]
  source = 'janebot_data'
  destination = '/data'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512
